# Generated by Django 5.0.7 on 2025-08-23 03:28

import django.db.models.deletion
import irrigation.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionriego',
            name='duracion',
            field=models.IntegerField(help_text='Duración en minutos'),
        ),
        migrations.CreateModel(
            name='ActivacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expiracion', models.DateTimeField(default=irrigation.models.fecha_expiracion_default)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
