# Generated by Django 5.0.7 on 2025-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_alter_programacionriego_duracion_activacionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
