# Generated by Django 5.0.7 on 2025-08-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_sensor_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='tipo',
            new_name='humedad',
        ),
    ]
