# Generated by Django 5.0.7 on 2025-08-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0004_rename_tipo_sensor_humedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='humedad',
            new_name='tipo',
        ),
    ]
