# Generated by Django 5.0.7 on 2025-08-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0005_rename_humedad_sensor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('humedad', 'Humedad'), ('temperatura', 'Temperatura')], max_length=12),
        ),
    ]
