# Generated by Django 5.0.7 on 2025-08-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0008_lecturasensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cultivo', models.CharField(max_length=100)),
                ('tipo_cultivo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
