# Generated by Django 5.0.7 on 2025-08-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0009_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionriego',
            name='numero_lotes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
