# Generated by Django 5.0.7 on 2025-09-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0010_programacionriego_numero_lotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacionriego',
            name='numero_lotes',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='numero_lotes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
