# Generated by Django 5.0.7 on 2025-09-13 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0011_remove_programacionriego_numero_lotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionriego',
            name='cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='irrigation.cultivo'),
        ),
    ]
