# Generated by Django 5.0.7 on 2025-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0012_programacionriego_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='numero_aspersores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
