# Generated by Django 5.0.7 on 2025-09-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0013_cultivo_numero_aspersores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('presentacion', models.TextField()),
            ],
        ),
    ]
