# Generated by Django 5.0.7 on 2025-09-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0016_alter_perfilusuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturasensor',
            name='cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='irrigation.cultivo'),
        ),
    ]
