# Generated by Django 5.0.7 on 2025-09-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0019_perfilusuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
