# Generated by Django 5.0.7 on 2025-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0020_perfilusuario_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado Bomba',
                'verbose_name_plural': 'Estados Bomba',
            },
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('humedad', 'Humedad')], max_length=12),
        ),
    ]
